package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка банера главной страницы")
    void generatedTest() {
        step("open https://www.esphere.ru/", () -> {
            open("https://www.esphere.ru");
        });

        step("check banner", () -> {
           $(".col-12").shouldBe(visible);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка заголовка главной страницы")
    void titleTest() {
        step("Open url 'https://www.esphere.ru/'", () ->
                open("https://www.esphere.ru"));

        step("Page title should have text 'СберКорус | КОРУС Консалтинг СНГ'", () -> {
            String expectedTitle = "СберКорус | КОРУС Консалтинг СНГ";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка ошибок в консоле")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.esphere.ru/'", () ->
                open("https://www.esphere.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}