package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка банера главной страницы")
    void checkBannerTest() {
        step("Открываем сайт https://www.esphere.ru/", () -> {
            open("https://www.esphere.ru");
        });

        step("check banner", () -> {
           $(".col-12").shouldBe(visible);
        });
    }

 @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка работы поиска")
    void searchValidationTest() {
        step("Открываем сайт https://www.esphere.ru/", () -> {
            open("https://www.esphere.ru");
        });

        step("Нажимаем на иконку поиска", () -> {
           $(".navigation-search__icon").click();
        });

        step("Вводим в поиске значение и нажимаем Enter", () -> {
         $(".navigation-search__input").setValue("ЭДО").pressEnter();
     });

         step("Проверяем отображение страницы поиска", () -> {
         $(".col-sm-10.col-sm-offset-1").shouldBe(visible);
     });
    }

 @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка раздела 'О компании'")
    void searchCompanyInformationTest() {
        step("Открываем сайт https://www.esphere.ru/", () -> {
            open("https://www.esphere.ru");
        });

        step("Заходим в раздел 'О компании'", () -> {
           $(".nav-item.nav-item__have-children.nav-item-have-children").click();
        });

        step("Проверка отображения страницы", () -> {
         $(".light-blue-gray-bg.col-xs-12.nopad").scrollTo().shouldBe(visible).shouldHave(text("Разработчик и провайдер облачных сервисов для автоматизации B2B процессов управления цепочками поставок и взаиморасчетов."));
     });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка заголовка главной страницы")
    void titleTest() {
        step("Открываем сайт 'https://www.esphere.ru/'", () ->
                open("https://www.esphere.ru"));

        step("Заголовок страницы должен иметь текст 'СберКорус | КОРУС Консалтинг СНГ'", () -> {
            String expectedTitle = "СберКорус | КОРУС Консалтинг СНГ";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка ошибок в консоле")
    void consoleShouldNotHaveErrorsTest() {
        step("Открываем сайт 'https://www.esphere.ru/'", () ->
                open("https://www.esphere.ru"));

        step("Журнал консоли не должны содержать текст 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}